services:
  supanova-server:
    image: jdgarner/supanova-server:latest
    container_name: supanova-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: .env.server
    network_mode: host # TODO: remove after postgres is inside docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${SERVER_PORT}/v2/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224" # TODO: change to fluent-bit:24224 after postgres is inside docker
        tag: "{{.Name}}"
        fluentd-async: "true"
        fluentd-max-retries: "5"

  supanova-maintenance:
    image: jdgarner/supanova-maintenance:latest
    container_name: supanova-maintenance
    env_file: .env.maintenance
    network_mode: host # TODO: remove after postgres is inside docker
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224" # TODO: change to fluent-bit:24224 after postgres is inside docker
        tag: "{{.Name}}"
        fluentd-async: "true"
        fluentd-max-retries: "5"

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    restart: unless-stopped
    env_file: .env.fluent-bit
    ports:
      - "24224:24224" # TODO: remove after postgres is inside docker
      - "24224:24224/udp"
    volumes:
      - ${HOME}/apps/supanova-infra/docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ${HOME}/apps/supanova-infra/docker/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
